# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1632aaafc26059007937de15c2cdf92b2957c22fc44ec0c9594b7fe4af30c63fbd95c5094b3becdc384a081bc87ed99044f859fbe0a99a282d18e8e369043ae

test:
  secret_key_base: 6e730c91cb9a0ce8beb15f90f920d2e6424751726e6fc281e60373ae85755f6ca33072213b61839a94461fd1b632a82d4c884a68dbea0f70840965096c6357bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
